### ISSUE TITLE
Allow to access pods via domain names

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#1885]
**Background**
At the moment pods are available from another pods via IP. For some cases, e.g. MPI clusters we manually add pod's hostnames and ips to `/etc/hosts` file to allow access to pods via hostname. It would be useful to allow access to a pod using some predefined hostname in an automated way using kubernetes DNS.

**Approach**
- Add the following fields to pod spec:
```
   - hostname: <POD_NAME>
   - subdomain: pods
   - dnsConfig:
      searches:
        - pods.default.svc.cluster.local
```       
         
- At application startup ensure that the following service exists:
```apiVersion: v1
kind: Service
metadata:
  name: pods
spec:
  selector:
    type: pipeline
  clusterIP: None
```
